Full path to vignettes
waldronlab/curatedMetagenomicAnalyses pull request #38
Opened 2022-02-14 10:38 UTC by d-golzato

Changed relative path to full path in README.md to fix links in pkgdown

2022-02-14 10:41 UTC, lwaldron reviewed
Looks good to me and should close #36 . @schifferl take a look and merge unless you have another idea.

2022-02-14 17:51 UTC, schifferl requested changes
Hi @d-golzato, the approach was correct, but the links were a little off. I made suggestions with the correct links that can be committed and then we will merge this pull request.

2022-02-14 17:51 UTC, schifferl commented on README.md
> +* [Create datasets for machine learning](https://github.com/waldronlab/curatedMetagenomicAnalyses/blob/vignettes/MLdatasets.Rmd)
```suggestion
* [Create datasets for machine learning](https://waldronlab.io/curatedMetagenomicAnalyses/articles/MLdatasets.html)
```

2022-02-15 11:01 UTC, d-golzato commented
Great, thanks @schifferl! Should I merge this pull request by myself?

2022-02-15 14:16 UTC, schifferl approved these changes

2022-02-15 14:18 UTC, merged

2022-02-15 14:18 UTC, schifferl commented
Good work @d-golzato, merging and closing now.